
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2017-08-26T11:21:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "2379eec92e0d6805dd2c669ad440b59a10d1e3d9",
 "version": "1.18.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
