/*
 * FILE : O:\src\pywin32\com\win32comext\mapi\src\exchange.cpp
 * 
 * This file was automatically generated by :
 * Simplified Wrapper and Interface Generator (SWIG)
 * Version 1.1 (Patch 5)
 * 
 * Portions Copyright (c) 1995-1998
 * The University of Utah and The Regents of the University of California.
 * Permission is granted to distribute this file in any manner provided
 * this notice remains intact.
 * 
 * Do not make changes to this file--changes will be lost!
 *
 */


#define SWIGCODE
/* Implementation : PYTHON */

#define SWIGPYTHON
#include <string.h>
#include <stdlib.h>
/***********************************************************************
 * $Header$
 * swig_lib/python/python.cfg
 *
 * This file contains coded needed to add variable linking to the
 * Python interpreter.   C variables are added as a new kind of Python
 * datatype.
 *
 * Also contains supporting code for building python under Windows
 * and things like that.
 *
 * $Log$
 * Revision 1.1  2000/03/14 23:34:06  mhammond
 * Needed to modify a standard Swig file to avoid the 'extern "C"' around Python.h (which gets upset when it tries to include whcar.h as part of the new Unicode patches)
 *
 ************************************************************************/

#include "Python.h"

/* Definitions for Windows/Unix exporting */
#if defined(__WIN32__)
#   if defined(_MSC_VER)
#	define SWIGEXPORT(a,b) __declspec(dllexport) a b
#   else
#	if defined(__BORLANDC__)
#	    define SWIGEXPORT(a,b) a _export b
#	else
#	    define SWIGEXPORT(a,b) a b
#	endif
#   endif
#else
#   define SWIGEXPORT(a,b) a b
#endif

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif

#ifdef NEED_SWIG_VARLINK

typedef struct {
  char  *name;
  PyObject *(*get_attr)(void);
  int (*set_attr)(PyObject *);
} swig_globalvar;

typedef struct swig_varlinkobject {
  PyObject_HEAD
  swig_globalvar **vars;
  int      nvars;
  int      maxvars;
} swig_varlinkobject;

/* ----------------------------------------------------------------------
   swig_varlink_repr()

   Function for python repr method
   ---------------------------------------------------------------------- */

static PyObject *
swig_varlink_repr(swig_varlinkobject *v)
{
  v = v;
  return PyString_FromString("<Global variables>");
}

/* ---------------------------------------------------------------------
   swig_varlink_print()

   Print out all of the global variable names
   --------------------------------------------------------------------- */

static int
swig_varlink_print(swig_varlinkobject *v, FILE *fp, int flags)
{

  int i = 0;
  flags = flags;
  fprintf(fp,"Global variables { ");
  while (v->vars[i]) {
    fprintf(fp,"%s", v->vars[i]->name);
    i++;
    if (v->vars[i]) fprintf(fp,", ");
  }
  fprintf(fp," }\n");
  return 0;
}

/* --------------------------------------------------------------------
   swig_varlink_getattr
 
   This function gets the value of a variable and returns it as a
   PyObject.   In our case, we'll be looking at the datatype and
   converting into a number or string
   -------------------------------------------------------------------- */

static PyObject *
swig_varlink_getattr(swig_varlinkobject *v, char *n)
{
  int i = 0;
  char temp[128];

  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->get_attr)();
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return NULL;
}

/* -------------------------------------------------------------------
   swig_varlink_setattr()

   This function sets the value of a variable.
   ------------------------------------------------------------------- */

static int
swig_varlink_setattr(swig_varlinkobject *v, char *n, PyObject *p)
{
  char temp[128];
  int i = 0;
  while (v->vars[i]) {
    if (strcmp(v->vars[i]->name,n) == 0) {
      return (*v->vars[i]->set_attr)(p);
    }
    i++;
  }
  sprintf(temp,"C global variable %s not found.", n);
  PyErr_SetString(PyExc_NameError,temp);
  return 1;
}

statichere PyTypeObject varlinktype = {
/*  PyObject_HEAD_INIT(&PyType_Type)  Note : This doesn't work on some machines */
  PyObject_HEAD_INIT(0)              
  0,
  "varlink",                          /* Type name    */
  sizeof(swig_varlinkobject),         /* Basic size   */
  0,                                  /* Itemsize     */
  0,                                  /* Deallocator  */ 
  (printfunc) swig_varlink_print,     /* Print        */
  (getattrfunc) swig_varlink_getattr, /* get attr     */
  (setattrfunc) swig_varlink_setattr, /* Set attr     */
  0,                                  /* tp_compare   */
  (reprfunc) swig_varlink_repr,       /* tp_repr      */    
  0,                                  /* tp_as_number */
  0,                                  /* tp_as_mapping*/
  0,                                  /* tp_hash      */
};

/* Create a variable linking object for use later */

SWIGSTATIC PyObject *
SWIG_newvarlink(void)
{
  swig_varlinkobject *result = 0;
  result = PyMem_NEW(swig_varlinkobject,1);
  varlinktype.ob_type = &PyType_Type;    /* Patch varlinktype into a PyType */
  result->ob_type = &varlinktype;
  /*  _Py_NewReference(result);  Does not seem to be necessary */
  result->nvars = 0;
  result->maxvars = 64;
  result->vars = (swig_globalvar **) malloc(64*sizeof(swig_globalvar *));
  result->vars[0] = 0;
  Py_XINCREF((PyObject *) result);
  return ((PyObject*) result);
}

SWIGSTATIC void
SWIG_addvarlink(PyObject *p, char *name,
	   PyObject *(*get_attr)(void), int (*set_attr)(PyObject *p))
{
  swig_varlinkobject *v;
  v= (swig_varlinkobject *) p;
	
  if (v->nvars >= v->maxvars -1) {
    v->maxvars = 2*v->maxvars;
    v->vars = (swig_globalvar **) realloc(v->vars,v->maxvars*sizeof(swig_globalvar *));
    if (v->vars == NULL) {
      fprintf(stderr,"SWIG : Fatal error in initializing Python module.\n");
      exit(1);
    }
  }
  v->vars[v->nvars] = (swig_globalvar *) malloc(sizeof(swig_globalvar));
  v->vars[v->nvars]->name = (char *) malloc(strlen(name)+1);
  strcpy(v->vars[v->nvars]->name,name);
  v->vars[v->nvars]->get_attr = get_attr;
  v->vars[v->nvars]->set_attr = set_attr;
  v->nvars++;
  v->vars[v->nvars] = 0;
}

#else
#define SWIG_newvarlink() Py_None
#endif /* SWIG_NEED_VARLINK */
#ifdef NEED_SWIG_PTR
/*****************************************************************************
 * $Header$
 *
 * swigptr.swg
 *
 * This file contains supporting code for the SWIG run-time type checking
 * mechanism.  The following functions are available :
 *
 * SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *));
 *
 *      Registers a new type-mapping with the type-checker.  origtype is the
 *      original datatype and newtype is an equivalent type.  cast is optional
 *      pointer to a function to cast pointer values between types (this
 *      is typically used to cast pointers from derived classes to base classes in C++)
 *      
 * SWIG_MakePtr(char *buffer, void *ptr, char *typestring);
 *     
 *      Makes a pointer string from a pointer and typestring.  The result is returned
 *      in buffer which is assumed to hold enough space for the result.
 *
 * char * SWIG_GetPtr(char *buffer, void **ptr, char *type)
 *
 *      Gets a pointer value from a string.  If there is a type-mismatch, returns
 *      a character string to the received type.  On success, returns NULL.
 *
 *
 * You can remap these functions by making a file called "swigptr.swg" in
 * your the same directory as the interface file you are wrapping.
 *
 * These functions are normally declared static, but this file can be
 * can be used in a multi-module environment by redefining the symbol
 * SWIGSTATIC.
 *****************************************************************************/

#include <stdlib.h>

#ifdef SWIG_GLOBAL
#ifdef __cplusplus
#define SWIGSTATIC extern "C"
#else
#define SWIGSTATIC
#endif
#endif

#ifndef SWIGSTATIC
#define SWIGSTATIC static
#endif


/* SWIG pointer structure */

typedef struct SwigPtrType {
  char               *name;               /* Datatype name                  */
  int                 len;                /* Length (used for optimization) */
  void               *(*cast)(void *);    /* Pointer casting function       */
  struct SwigPtrType *next;               /* Linked list pointer            */
} SwigPtrType;

/* Pointer cache structure */

typedef struct {
  int                 stat;               /* Status (valid) bit             */
  SwigPtrType        *tp;                 /* Pointer to type structure      */
  char                name[256];          /* Given datatype name            */
  char                mapped[256];        /* Equivalent name                */
} SwigCacheType;

/* Some variables  */

static int SwigPtrMax  = 64;           /* Max entries that can be currently held */
                                       /* This value may be adjusted dynamically */
static int SwigPtrN    = 0;            /* Current number of entries              */
static int SwigPtrSort = 0;            /* Status flag indicating sort            */
static int SwigStart[256];             /* Starting positions of types            */

/* Pointer table */
static SwigPtrType *SwigPtrTable = 0;  /* Table containing pointer equivalences  */

/* Cached values */

#define SWIG_CACHESIZE  8
#define SWIG_CACHEMASK  0x7
static SwigCacheType SwigCache[SWIG_CACHESIZE];  
static int SwigCacheIndex = 0;
static int SwigLastCache = 0;

/* Sort comparison function */
static int swigsort(const void *data1, const void *data2) {
	SwigPtrType *d1 = (SwigPtrType *) data1;
	SwigPtrType *d2 = (SwigPtrType *) data2;
	return strcmp(d1->name,d2->name);
}

/* Binary Search function */
static int swigcmp(const void *key, const void *data) {
  char *k = (char *) key;
  SwigPtrType *d = (SwigPtrType *) data;
  return strncmp(k,d->name,d->len);
}

/* Register a new datatype with the type-checker */

SWIGSTATIC 
void SWIG_RegisterMapping(char *origtype, char *newtype, void *(*cast)(void *)) {

  int i;
  SwigPtrType *t = 0,*t1;

  /* Allocate the pointer table if necessary */

  if (!SwigPtrTable) {     
    SwigPtrTable = (SwigPtrType *) malloc(SwigPtrMax*sizeof(SwigPtrType));
    SwigPtrN = 0;
  }
  /* Grow the table */
  if (SwigPtrN >= SwigPtrMax) {
    SwigPtrMax = 2*SwigPtrMax;
    SwigPtrTable = (SwigPtrType *) realloc((char *) SwigPtrTable,SwigPtrMax*sizeof(SwigPtrType));
  }
  for (i = 0; i < SwigPtrN; i++)
    if (strcmp(SwigPtrTable[i].name,origtype) == 0) {
      t = &SwigPtrTable[i];
      break;
    }
  if (!t) {
    t = &SwigPtrTable[SwigPtrN];
    t->name = origtype;
    t->len = strlen(t->name);
    t->cast = 0;
    t->next = 0;
    SwigPtrN++;
  }

  /* Check for existing entry */

  while (t->next) {
    if ((strcmp(t->name,newtype) == 0)) {
      if (cast) t->cast = cast;
      return;
    }
    t = t->next;
  }
  
  /* Now place entry (in sorted order) */

  t1 = (SwigPtrType *) malloc(sizeof(SwigPtrType));
  t1->name = newtype;
  t1->len = strlen(t1->name);
  t1->cast = cast;
  t1->next = 0;            
  t->next = t1;           
  SwigPtrSort = 0;
}

/* Make a pointer value string */

SWIGSTATIC 
void SWIG_MakePtr(char *_c, const void *_ptr, char *type) {
  static char _hex[16] =
  {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',
   'a', 'b', 'c', 'd', 'e', 'f'};
  unsigned long _p, _s;
  char _result[20], *_r;    /* Note : a 64-bit hex number = 16 digits */
  _r = _result;
  _p = (unsigned long) _ptr;
  if (_p > 0) {
    while (_p > 0) {
      _s = _p & 0xf;
      *(_r++) = _hex[_s];
      _p = _p >> 4;
    }
    *_r = '_';
    while (_r >= _result)
      *(_c++) = *(_r--);
  } else {
    strcpy (_c, "NULL");
  }
  if (_ptr)
    strcpy (_c, type);
}

/* Define for backwards compatibility */

#define _swig_make_hex   SWIG_MakePtr 

/* Function for getting a pointer value */

SWIGSTATIC 
char *SWIG_GetPtr(char *_c, void **ptr, char *_t)
{
  unsigned long _p;
  char temp_type[256];
  char *name;
  int  i, len;
  SwigPtrType *sp,*tp;
  SwigCacheType *cache;
  int  start, end;
  _p = 0;

  /* Pointer values must start with leading underscore */
  if (*_c == '_') {
      _c++;
      /* Extract hex value from pointer */
      while (*_c) {
	  if ((*_c >= '0') && (*_c <= '9'))
	    _p = (_p << 4) + (*_c - '0');
	  else if ((*_c >= 'a') && (*_c <= 'f'))
	    _p = (_p << 4) + ((*_c - 'a') + 10);
	  else
	    break;
	  _c++;
      }

      if (_t) {
	if (strcmp(_t,_c)) { 
	  if (!SwigPtrSort) {
	    qsort((void *) SwigPtrTable, SwigPtrN, sizeof(SwigPtrType), swigsort); 
	    for (i = 0; i < 256; i++) {
	      SwigStart[i] = SwigPtrN;
	    }
	    for (i = SwigPtrN-1; i >= 0; i--) {
	      SwigStart[(int) (SwigPtrTable[i].name[1])] = i;
	    }
	    for (i = 255; i >= 1; i--) {
	      if (SwigStart[i-1] > SwigStart[i])
		SwigStart[i-1] = SwigStart[i];
	    }
	    SwigPtrSort = 1;
	    for (i = 0; i < SWIG_CACHESIZE; i++)  
	      SwigCache[i].stat = 0;
	  }
	  
	  /* First check cache for matches.  Uses last cache value as starting point */
	  cache = &SwigCache[SwigLastCache];
	  for (i = 0; i < SWIG_CACHESIZE; i++) {
	    if (cache->stat) {
	      if (strcmp(_t,cache->name) == 0) {
		if (strcmp(_c,cache->mapped) == 0) {
		  cache->stat++;
		  *ptr = (void *) _p;
		  if (cache->tp->cast) *ptr = (*(cache->tp->cast))(*ptr);
		  return (char *) 0;
		}
	      }
	    }
	    SwigLastCache = (SwigLastCache+1) & SWIG_CACHEMASK;
	    if (!SwigLastCache) cache = SwigCache;
	    else cache++;
	  }
	  /* We have a type mismatch.  Will have to look through our type
	     mapping table to figure out whether or not we can accept this datatype */

	  start = SwigStart[(int) _t[1]];
	  end = SwigStart[(int) _t[1]+1];
	  sp = &SwigPtrTable[start];
	  while (start < end) {
	    if (swigcmp(_t,sp) == 0) break;
	    sp++;
	    start++;
	  }
	  if (start >= end) sp = 0;
	  /* Try to find a match for this */
	  if (sp) {
	    while (swigcmp(_t,sp) == 0) {
	      name = sp->name;
	      len = sp->len;
	      tp = sp->next;
	      /* Try to find entry for our given datatype */
	      while(tp) {
		if (tp->len >= 255) {
		  return _c;
		}
		strncpy(temp_type,tp->name,255);
		strncat(temp_type,_t+len,255-tp->len);
		if (strcmp(_c,temp_type) == 0) {
		  
		  strcpy(SwigCache[SwigCacheIndex].mapped,_c);
		  strcpy(SwigCache[SwigCacheIndex].name,_t);
		  SwigCache[SwigCacheIndex].stat = 1;
		  SwigCache[SwigCacheIndex].tp = tp;
		  SwigCacheIndex = SwigCacheIndex & SWIG_CACHEMASK;
		  
		  /* Get pointer value */
		  *ptr = (void *) _p;
		  if (tp->cast) *ptr = (*(tp->cast))(*ptr);
		  return (char *) 0;
		}
		tp = tp->next;
	      }
	      sp++;
	      /* Hmmm. Didn't find it this time */
	    }
	  }
	  /* Didn't find any sort of match for this data.  
	     Get the pointer value and return the received type */
	  *ptr = (void *) _p;
	  return _c;
	} else {
	  /* Found a match on the first try.  Return pointer value */
	  *ptr = (void *) _p;
	  return (char *) 0;
	}
      } else {
	/* No type specified.  Good luck */
	*ptr = (void *) _p;
	return (char *) 0;
      }
  } else {
    if (strcmp (_c, "NULL") == 0) {
	*ptr = (void *) 0;
	return (char *) 0;
    }
    *ptr = (void *) 0;	
    return _c;
  }
}

/* Compatibility mode */

#define _swig_get_hex  SWIG_GetPtr

#else
#define SWIG_RegisterMapping(a,b,c)
#endif // NEED_SWIG_PTR
#define SWIG_init    initexchange

#define SWIG_name    "exchange"

// #define UNICODE
// #define _UNICODE

static PyObject* t_output_helper(PyObject* target, PyObject* o) {
    PyObject*   o2;
    PyObject*   o3;

    if (!target) {                   
        target = o;
    } else if (target == Py_None) {  
        Py_DECREF(Py_None);
        target = o;
    } else {                            
        if (!PyTuple_Check(target)) {   
            o2 = target;
            target = PyTuple_New(1);
            PyTuple_SetItem(target, 0, o2);
        }
        o3 = PyTuple_New(1);            
        PyTuple_SetItem(o3, 0, o);      

        o2 = target;
        target = PySequence_Concat(o2, o3); 
        Py_DECREF(o2);                      
        Py_DECREF(o3);
    }
    return target;
}

#include "PyWinTypes.h"
#ifdef NEED_PYWINOBJECTS_H
#include "PyWinObjects.h"
#endif
#include "tchar.h"
typedef BOOL  BOOLAPI;
typedef DWORD  DWORDAPI;

#define PyHANDLE HANDLE // Use a #define so we can undef it later if we need the true defn.
//typedef HANDLE PyHKEY;

#include "PythonCOM.h"

#define SWIG_PYTHONCOM
typedef long  HRESULT_KEEP;
typedef long  HRESULT_KEEP_INFO;

#define MAKE_OUTPUT_INTERFACE(source, target, iid) \
{ \
    PyObject *o; \
    o = PyCom_PyObjectFromIUnknown(*source, iid, FALSE /* bAddRef */); \
    if (target==NULL) \
      target = o; \
	else if (target == Py_None) { /* has been incref'd already!*/ \
		Py_DECREF(Py_None); \
		target = o; \
    } else { \
      if (!PyList_Check(target)) { \
        PyObject *o2 = target; \
        target = PyList_New(0); \
        PyList_Append(target,o2); \
        Py_XDECREF(o2); \
      } \
      PyList_Append(target,o); \
      Py_XDECREF(o); \
    } \
}

#include "pymapiutil.h"

#include "PythonCOMServer.h"
#include "PythonCOMRegister.h"

#include "MAPIUTIL.H"
#include "EDKMDB.H"

#define USES_IID_IExchangeManageStore
#include <edkguid.h>

#include "PyIExchangeManageStore.h"

#include "EDKMAPI.H"
#include "EDKCFG.H"
#include "EDKUTILS.H"

// What is the correct story here??  The Exchange SDK story sucks - it seems
// certain functions in the stand-alone version are simply commented out.
#if defined(EXCHANGE_RE)
#	define DONT_HAVE_MBLOGON
#	define DONT_HAVE_ADDRLKUP
#endif

#if !defined(DONT_HAVE_ADDRLKUP)
#	include "ADDRLKUP.H"
#endif
#if !defined(DONT_HAVE_MBLOGON)
#	include "MBLOGON.H"
#endif

static int AddIID(PyObject *dict, const char *key, REFGUID guid)
{
	PyObject *obiid = PyWinObject_FromIID(guid);
	if (!obiid) return 1;
	int rc = PyDict_SetItemString(dict, (char*)key, obiid);
	Py_DECREF(obiid);
	return rc;
}


#define ADD_IID(tok) AddIID(d, #tok, tok)


// @pyswig string|HrMAPIFindDefaultMsgStore|Retrieves the entry identifier of the default information store.
static PyObject *PyHrMAPIFindDefaultMsgStore(PyObject *self, PyObject *args) 
{
    HRESULT  _result;
	ULONG entryStrLen;
	ENTRYID *pID;
    IMAPISession * pS = NULL;
	PyObject *obSession;

	// @pyparm <o PyIMAPISession>|session||
    if(!PyArg_ParseTuple(args,"O:HrMAPIFindDefaultMsgStore",&obSession)) 
        return NULL;

	if (!PyCom_InterfaceFromPyInstanceOrObject(obSession, IID_IMAPISession, (void **)&pS, 0))
		return NULL;

     _result = (HRESULT )HrMAPIFindDefaultMsgStore(pS, &entryStrLen, &pID);
     if (FAILED(_result)) {
           return OleSetOleError(_result);
     }
	 PyObject *rc = PyString_FromStringAndSize((char *)pID, entryStrLen);
	 MAPIFreeBuffer(pID);
	 return rc;
}

// @pyswig string|HrMAPIFindIPMSubtree|Retrieves the entry ID of the IPM (interpersonal message) subtree folder
static PyObject *PyHrMAPIFindIPMSubtree(PyObject *self, PyObject *args) 
{
    HRESULT  _result;
	ULONG entryStrLen;
	ENTRYID *pID;
    IMsgStore * pS = NULL;
	PyObject *obStore;

	// @pyparm <o PyIMsgStore>|msgStore||
    if(!PyArg_ParseTuple(args,"O:HrMAPIFindIPMSubtree",&obStore)) 
        return NULL;

	if (!PyCom_InterfaceFromPyInstanceOrObject(obStore, IID_IMsgStore, (void **)&pS, 0))
		return NULL;

     _result = (HRESULT )HrMAPIFindIPMSubtree(pS, &entryStrLen, &pID);
     if (FAILED(_result)) {
           return OleSetOleError(_result);
     }
	 PyObject *rc = PyString_FromStringAndSize((char *)pID, entryStrLen);
	 MAPIFreeBuffer(pID);
	 return rc;
}

// @pyswig string|HrMAPIFindInbox|Retrieves the Entry ID of the IPM inbox folder
static PyObject *PyHrMAPIFindInbox(PyObject *self, PyObject *args) 
{
    HRESULT  _result;
	ULONG entryStrLen;
	ENTRYID *pID;
    IMsgStore * pS = NULL;
	PyObject *obStore;

	// @pyparm <o PyIMsgStore>|msgStore||
    if(!PyArg_ParseTuple(args,"O:HrMAPIFindInbox",&obStore)) 
        return NULL;

	if (!PyCom_InterfaceFromPyInstanceOrObject(obStore, IID_IMsgStore, (void **)&pS, 0))
		return NULL;

     _result = (HRESULT )HrMAPIFindInbox(pS, &entryStrLen, &pID);
     if (FAILED(_result)) {
           return OleSetOleError(_result);
     }
	 PyObject *rc = PyString_FromStringAndSize((char *)pID, entryStrLen);
	 MAPIFreeBuffer(pID);
	 return rc;
}

PyObject *MyHrMAPIFindSubfolderEx(
	IMAPIFolder *lpRootFolder,
	TCHAR chSep,
	TCHAR *lpszName) 
{
	DWORD idSize;
	ENTRYID *id;
	HRESULT hr = HrMAPIFindSubfolderEx(lpRootFolder,chSep,lpszName,&idSize, &id);
	if (FAILED(hr))
		return OleSetOleError(hr);
	PyObject *rc = PyString_FromStringAndSize((char *)id, idSize);
	MAPIFreeBuffer(id);
	return rc;
}

PyObject *PyHrMAPIFindFolder(PyObject *self, PyObject *args)
{
	PyObject *obFolder;
	PyObject *obName;
	ULONG cbEID;
	LPENTRYID eid;
	HRESULT hr;
	PyObject *rc = NULL;
	if (!PyArg_ParseTuple(args, "OO:HrMAPIFindFolder",
		&obFolder, // @pyparm <o PyIMAPIFolder>|folder||The folder to search
		&obName))// @pyparm string|name||Name of the folder
		return NULL;
	TCHAR *szName = NULL;
	IMAPIFolder *pFolder = NULL;
	if (!PyWinObject_AsTCHAR(obName, &szName))
		goto done;
	if (!PyCom_InterfaceFromPyObject(obFolder, IID_IMAPIFolder, (void **)&pFolder, FALSE))
		goto done;
	{
	PY_INTERFACE_PRECALL;
	hr = HrMAPIFindFolder(pFolder, szName, &cbEID, &eid);
	PY_INTERFACE_POSTCALL;
	}
	if (FAILED(hr)) {
		OleSetOleError(hr);
		goto done;
	}
	rc = PyString_FromStringAndSize((char *)eid, cbEID);
done:
	if (pFolder) pFolder->Release();
	if (szName) PyWinObject_FreeTCHAR(szName);
	return rc;
}

PyObject *PyHrMAPIFindFolderEx(PyObject *self, PyObject *args)
{
	PyObject *obMDB;
	PyObject *obSep, *obPath;
	ULONG cbEID;
	LPENTRYID eid;
	HRESULT hr;
	PyObject *rc = NULL;
	if (!PyArg_ParseTuple(args, "OOO:HrMAPIFindFolderEx",
		&obMDB, // @pyparm <o PyIMsgStore>|msgStore||The folder to search
		&obSep, // @pyparm string|sepString||The character seperating the folder names - eg '\'
		&obPath))// @pyparm string|path||Path to the folder
		return NULL;
	TCHAR *szSep = NULL, *szPath = NULL;
	IMsgStore *pMDB = NULL;
	if (!PyWinObject_AsTCHAR(obSep, &szSep))
		goto done;
	if (!PyWinObject_AsTCHAR(obPath, &szPath))
		goto done;
	if (!PyCom_InterfaceFromPyObject(obMDB, IID_IMsgStore, (void **)&pMDB, FALSE))
		goto done;
	{
	PY_INTERFACE_PRECALL;
	hr = HrMAPIFindFolderEx(pMDB, szSep[0], szPath, &cbEID, &eid);
	PY_INTERFACE_POSTCALL;
	}
	if (FAILED(hr)) {
		OleSetOleError(hr);
		goto done;
	}
	rc = PyString_FromStringAndSize((char *)eid, cbEID);
done:
	if (pMDB) pMDB->Release();
	if (szSep) PyWinObject_FreeTCHAR(szSep);
	if (szPath) PyWinObject_FreeTCHAR(szPath);
	return rc;
}

PyObject *PyHrMAPIFindStore(PyObject *self, PyObject *args)
{
	PyObject *obSession;
	PyObject *obName;
	ULONG cbEID;
	LPENTRYID eid;
	HRESULT hr;
	PyObject *rc = NULL;
	if (!PyArg_ParseTuple(args, "OO:HrMAPIFindStore",
		&obSession, // @pyparm <o PyIMAPISession>|session||
		&obName)) // @pyparm string|name||
		return NULL;
	TCHAR *szName = NULL;
	IMAPISession *pSession = NULL;
	if (!PyWinObject_AsTCHAR(obName, &szName))
		goto done;
	if (!PyCom_InterfaceFromPyObject(obSession, IID_IMAPISession, (void **)&pSession, FALSE))
		goto done;
	{
	PY_INTERFACE_PRECALL;
	hr = HrMAPIFindStore(pSession, szName, &cbEID, &eid);
	PY_INTERFACE_POSTCALL;
	}
	if (FAILED(hr)) {
		OleSetOleError(hr);
		goto done;
	}
	rc = PyString_FromStringAndSize((char *)eid, cbEID);
done:
	if (pSession) pSession->Release();
	if (szName) PyWinObject_FreeTCHAR(szName);
	return rc;
}

// @pyswig string|HrCreateProfileName|Creates a profile with the specified name
static PyObject *PyHrCreateProfileName(PyObject *self, PyObject *args) 
{
    HRESULT  _result;
	PyObject *obPrefix;
	char *prefix;
	// @pyparm string/<o PyUnicode>|profPrefix||A prefix for the new profile.
	if (!PyArg_ParseTuple(args, "O:HrCreateProfileName", &obPrefix))
		return NULL;
	if (!PyWinObject_AsString(obPrefix, &prefix))
		return NULL;
	const int bufSize = MAX_PATH + 1;
	char buf[bufSize];
	_result = HrCreateProfileName(prefix, bufSize, buf);
	PyWinObject_FreeString(prefix);
	if (FAILED(_result))
		return OleSetOleError(_result);
	return PyWinCoreString_FromString(buf);
}

PyObject *PyHrCreateDirEntryIdEx(PyObject *self, PyObject *args)
{
	PyObject *ret = NULL;
	IAddrBook *pAddrBook;
	PyObject *obAddrBook, *obDN;
	char *szdn = NULL;
	LPENTRYID entryId;
	HRESULT hr;
	ULONG cbEntryId;
	if (!PyArg_ParseTuple(args, "OO:HrCreateDirEntryIdEx", 
		&obAddrBook, // @pyparm <o PyIAddrBook>|addrBook||The address book interface
		&obDN))		 // @pyparm string|distinguishedName||The dn of the object to obtain the entry ID for.
		return NULL;

	if (!PyWinObject_AsString(obDN, &szdn, FALSE))
        goto done;

	if (!PyCom_InterfaceFromPyInstanceOrObject(obAddrBook, IID_IAddrBook, (void **)&pAddrBook, /*BOOL bNoneOK=*/FALSE))
		goto done;

	hr = HrCreateDirEntryIdEx(pAddrBook, szdn, &cbEntryId, &entryId);
	if (FAILED(hr))
		return OleSetOleError(hr);

	ret = PyString_FromStringAndSize((char *)entryId, cbEntryId);
done:
	PyWinObject_FreeString(szdn);
	if (pAddrBook) pAddrBook->Release();
	return ret;
}

// @pyswig string|HrFindExchangeGlobalAddressList|Retrieves the entry identifier of the global address list (GAL) container in the address book.
static PyObject *PyHrFindExchangeGlobalAddressList(PyObject *self, PyObject *args) 
{
#ifdef DONT_HAVE_ADDRLKUP
	return PyErr_Format(PyExc_NotImplementedError, "Not available with this version of the Exchange SDK");
#else
	PyObject *obAddrBook;
	// @pyparm <o PyIAddrBook>|addrBook||The interface containing the address book
	if (!PyArg_ParseTuple(args, "O:HrFindExchangeGlobalAddressList", &obAddrBook))
		return NULL;

	IAddrBook *pAB;
	ULONG cb;
	LPENTRYID peid;
	if (!PyCom_InterfaceFromPyInstanceOrObject(obAddrBook, IID_IAddrBook, (void **)&pAB, 0))
		return NULL;
	HRESULT _result = HrFindExchangeGlobalAddressList(pAB, &cb, &peid);
    if (FAILED(_result)) {
           return OleSetOleError(_result);
     }

	PyObject *rc = PyString_FromStringAndSize((char *)peid, cb);
	MAPIFreeBuffer(peid);
	return rc;
#endif
}

HRESULT MyHrMailboxLogon(
    IN  LPMAPISESSION   lplhSession,                // ptr to MAPI session handle
    IN  LPMDB           lpMDB,                      // ptr to message store
    IN  LPSTR           lpszMsgStoreDN,             // ptr to message store DN
    IN  LPSTR           lpszMailboxDN,              // ptr to mailbox DN
    OUT LPMDB           *lppMailboxMDB)            // ptr to mailbox message store ptr
{
#if defined(DONT_HAVE_MBLOGON)
	PyErr_Warn(PyExc_RuntimeWarning, "Not available with this version of the Exchange SDK");
	return E_NOTIMPL;
#else
	return HrMailboxLogon(lplhSession, lpMDB, lpszMsgStoreDN, lpszMailboxDN, lppMailboxMDB);
#endif
}

HRESULT MyHrMailboxLogoff(IMsgStore **pp)
{
#if defined(DONT_HAVE_MBLOGON)
	PyErr_Warn(PyExc_RuntimeWarning, "Not available with this version of the Exchange SDK");
	return E_NOTIMPL;
#else
	return HrMailboxLogoff(pp);
#endif
}
static PyObject *_wrap_HrGetExchangeStatus(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    char * _arg0;
    unsigned long * _arg1;
    unsigned long  temp;
    unsigned long * _arg2;
    unsigned long  temp0;

    self = self;
{
  _arg1 = &temp;
}
{
  _arg2 = &temp0;
}
    if(!PyArg_ParseTuple(args,"s:HrGetExchangeStatus",&_arg0)) 
        return NULL;
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )HrGetExchangeStatus(_arg0,_arg1,_arg2);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           
#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
    PyObject *o;
    o = PyInt_FromLong((long) (*_arg1));
    if (!_resultobj) {
      _resultobj = o;
    } else if (_resultobj == Py_None) {
      Py_DECREF(Py_None);
      _resultobj = o;
    } else {
      if (!PyList_Check(_resultobj)) {
	PyObject *o2 = _resultobj;
	_resultobj = PyList_New(0);
	PyList_Append(_resultobj,o2);
	Py_XDECREF(o2);
      }
      PyList_Append(_resultobj,o);
      Py_XDECREF(o);
    }
}
{
    PyObject *o;
    o = PyInt_FromLong((long) (*_arg2));
    if (!_resultobj) {
      _resultobj = o;
    } else if (_resultobj == Py_None) {
      Py_DECREF(Py_None);
      _resultobj = o;
    } else {
      if (!PyList_Check(_resultobj)) {
	PyObject *o2 = _resultobj;
	_resultobj = PyList_New(0);
	PyList_Append(_resultobj,o2);
	Py_XDECREF(o2);
      }
      PyList_Append(_resultobj,o);
      Py_XDECREF(o);
    }
}
    return _resultobj;
}

static PyObject *_wrap_HrGetMailboxDN(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    IMAPISession * _arg0;
    char ** _arg1;
    char * temp;
    PyObject * _obj0 = 0;

    self = self;
{
	_arg0 = NULL;
}
{
  _arg1 = &temp;
}
    if(!PyArg_ParseTuple(args,"O:HrGetMailboxDN",&_obj0)) 
        return NULL;
{
	if (!PyCom_InterfaceFromPyInstanceOrObject(_obj0, IID_IMAPISession, (void **)&_arg0, 0))
		return NULL;
}
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )HrGetMailboxDN(_arg0,_arg1);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           {
	if (_arg0) _arg0->Release();
}

#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
	if (*_arg1==NULL) {
		_resultobj = Py_None;
		Py_INCREF(Py_None);
	} else {
		_resultobj = PyWinCoreString_FromString(*_arg1);
		MAPIFreeBuffer(*_arg1);
	}
}
{
	if (_arg0) _arg0->Release();
}
    return _resultobj;
}

static PyObject *_wrap_HrGetServerDN(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    IMAPISession * _arg0;
    char ** _arg1;
    char * temp;
    PyObject * _obj0 = 0;

    self = self;
{
	_arg0 = NULL;
}
{
  _arg1 = &temp;
}
    if(!PyArg_ParseTuple(args,"O:HrGetServerDN",&_obj0)) 
        return NULL;
{
	if (!PyCom_InterfaceFromPyInstanceOrObject(_obj0, IID_IMAPISession, (void **)&_arg0, 0))
		return NULL;
}
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )HrGetServerDN(_arg0,_arg1);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           {
	if (_arg0) _arg0->Release();
}

#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
	if (*_arg1==NULL) {
		_resultobj = Py_None;
		Py_INCREF(Py_None);
	} else {
		_resultobj = PyWinCoreString_FromString(*_arg1);
		MAPIFreeBuffer(*_arg1);
	}
}
{
	if (_arg0) _arg0->Release();
}
    return _resultobj;
}

static PyObject *_wrap_HrMAPIFindSubfolderEx(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    PyObject * _result;
    IMAPIFolder * _arg0;
    TCHAR * _arg1;
    TCHAR * _arg2;
    PyObject * _obj0 = 0;
    PyObject * _obj1 = 0;
    PyObject * _obj2 = 0;

    self = self;
{
	_arg0 = NULL;
}
{
	_arg1 = NULL;
}
{
	_arg2 = NULL;
}
    if(!PyArg_ParseTuple(args,"OOO:HrMAPIFindSubfolderEx",&_obj0,&_obj1,&_obj2)) 
        return NULL;
{
	if (!PyCom_InterfaceFromPyInstanceOrObject(_obj0, IID_IMAPIFolder, (void **)&_arg0, 0))
		return NULL;
}
{
	if (!PyWinObject_AsTCHAR(_obj1, &_arg1, FALSE))
		return NULL;
}
{
	if (!PyWinObject_AsTCHAR(_obj2, &_arg2, FALSE))
		return NULL;
}
    _result = (PyObject *)MyHrMAPIFindSubfolderEx(_arg0,*_arg1,_arg2);
{
	if (_result==NULL) return NULL; // get out now!
	_resultobj = _result;
}
{
	if (_arg0) _arg0->Release();
}
{
	PyWinObject_FreeTCHAR(_arg1);
}
{
	PyWinObject_FreeTCHAR(_arg2);
}
    return _resultobj;
}

static PyObject *_wrap_HrMailboxLogon(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    IMAPISession * _arg0;
    IMsgStore * _arg1;
    char * _arg2;
    char * _arg3;
    IMsgStore ** _arg4;
    IMsgStore * temp;
    PyObject * _obj0 = 0;
    PyObject * _obj1 = 0;

    self = self;
{
	_arg0 = NULL;
}
{
	_arg4 = NULL;
}
{
  _arg4 = &temp;
}
    if(!PyArg_ParseTuple(args,"OOss:HrMailboxLogon",&_obj0,&_obj1,&_arg2,&_arg3)) 
        return NULL;
{
	if (!PyCom_InterfaceFromPyInstanceOrObject(_obj0, IID_IMAPISession, (void **)&_arg0, 0))
		return NULL;
}
{
	if (!PyCom_InterfaceFromPyInstanceOrObject(_obj1, IID_IMsgStore, (void **)&_arg1, 0))
		return NULL;
}
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )MyHrMailboxLogon(_arg0,_arg1,_arg2,_arg3,_arg4);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           {
	if (_arg0) _arg0->Release();
}
{
	if (_arg1) _arg1->Release();
}

#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
	MAKE_OUTPUT_INTERFACE(_arg4, _resultobj, IID_IMsgStore)
}
{
	if (_arg0) _arg0->Release();
}
{
	if (_arg1) _arg1->Release();
}
    return _resultobj;
}

static PyObject *_wrap_HrMailboxLogoff(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    IMsgStore ** _arg0;
    IMsgStore * temp;
    PyObject * _obj0 = 0;

    self = self;
{
	_arg0 = NULL;
}
    if(!PyArg_ParseTuple(args,"O:HrMailboxLogoff",&_obj0)) 
        return NULL;
{
	_arg0 = &temp;
	if (!PyCom_InterfaceFromPyInstanceOrObject(_obj0, IID_IMsgStore, (void **)_arg0, 0))
		return NULL;
}
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )MyHrMailboxLogoff(_arg0);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           {
	if (_arg0 && *_arg0) (*_arg0)->Release();
}

#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
	if (_arg0 && *_arg0) (*_arg0)->Release();
}
    return _resultobj;
}

static PyObject *_wrap_HrMAPIOpenFolderEx(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    IMsgStore * _arg0;
    WCHAR * _arg1;
    WCHAR * _arg2;
    IMAPIFolder ** _arg3;
    IMAPIFolder * temp;
    PyObject * _obj0 = 0;
    PyObject * _obj1 = 0;
    PyObject * _obj2 = 0;

    self = self;
{
	_arg1 = NULL;
}
{
	_arg2 = NULL;
}
{
  _arg3 = &temp;
}
    if(!PyArg_ParseTuple(args,"OOO:HrMAPIOpenFolderEx",&_obj0,&_obj1,&_obj2)) 
        return NULL;
{
	if (!PyCom_InterfaceFromPyInstanceOrObject(_obj0, IID_IMsgStore, (void **)&_arg0, 1))
		return NULL;
}
{
	// Wide string code!
	if (!PyWinObject_AsWCHAR(_obj1, &_arg1, FALSE))
		return NULL;
}
{
	// Wide string code!
	if (!PyWinObject_AsWCHAR(_obj2, &_arg2, FALSE))
		return NULL;
}
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )HrMAPIOpenFolderExW(_arg0,*_arg1,_arg2,_arg3);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           {
	if (_arg0) _arg0->Release();
}
{
	// Wide string cleanup
	PyWinObject_FreeWCHAR(_arg1);
}
{
	// Wide string cleanup
	PyWinObject_FreeWCHAR(_arg2);
}

#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
	MAKE_OUTPUT_INTERFACE(_arg3, _resultobj, IID_IMAPIFolder)
}
{
	if (_arg0) _arg0->Release();
}
{
	// Wide string cleanup
	PyWinObject_FreeWCHAR(_arg1);
}
{
	// Wide string cleanup
	PyWinObject_FreeWCHAR(_arg2);
}
    return _resultobj;
}

static PyObject *_wrap_HrMAPISetPropBoolean(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    IMAPIProp * _arg0;
    unsigned long  _arg1;
    int  _arg2;
    PyObject * _obj0 = 0;

    self = self;
{
	_arg0 = NULL;
}
    if(!PyArg_ParseTuple(args,"Oli:HrMAPISetPropBoolean",&_obj0,&_arg1,&_arg2)) 
        return NULL;
{
	if (!PyCom_InterfaceFromPyInstanceOrObject(_obj0, IID_IMAPIProp, (void **)&_arg0, 0))
		return NULL;
}
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )HrMAPISetPropBoolean(_arg0,_arg1,_arg2);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           {
	if (_arg0) _arg0->Release();
}

#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
	if (_arg0) _arg0->Release();
}
    return _resultobj;
}

static PyObject *_wrap_HrMAPISetPropLong(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    IMAPIProp * _arg0;
    unsigned long  _arg1;
    long  _arg2;
    PyObject * _obj0 = 0;

    self = self;
{
	_arg0 = NULL;
}
    if(!PyArg_ParseTuple(args,"Oll:HrMAPISetPropLong",&_obj0,&_arg1,&_arg2)) 
        return NULL;
{
	if (!PyCom_InterfaceFromPyInstanceOrObject(_obj0, IID_IMAPIProp, (void **)&_arg0, 0))
		return NULL;
}
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )HrMAPISetPropLong(_arg0,_arg1,_arg2);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           {
	if (_arg0) _arg0->Release();
}

#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
	if (_arg0) _arg0->Release();
}
    return _resultobj;
}

static PyObject *_wrap_HrOpenExchangePublicStore(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    IMAPISession * _arg0;
    IMsgStore ** _arg1;
    IMsgStore * temp;
    PyObject * _obj0 = 0;

    self = self;
{
	_arg0 = NULL;
}
{
	_arg1 = NULL;
}
{
  _arg1 = &temp;
}
    if(!PyArg_ParseTuple(args,"O:HrOpenExchangePublicStore",&_obj0)) 
        return NULL;
{
	if (!PyCom_InterfaceFromPyInstanceOrObject(_obj0, IID_IMAPISession, (void **)&_arg0, 0))
		return NULL;
}
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )HrOpenExchangePublicStore(_arg0,_arg1);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           {
	if (_arg0) _arg0->Release();
}

#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
	MAKE_OUTPUT_INTERFACE(_arg1, _resultobj, IID_IMsgStore)
}
{
	if (_arg0) _arg0->Release();
}
    return _resultobj;
}

static PyObject *_wrap_HrOpenExchangePrivateStore(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    IMAPISession * _arg0;
    IMsgStore ** _arg1;
    IMsgStore * temp;
    PyObject * _obj0 = 0;

    self = self;
{
	_arg0 = NULL;
}
{
	_arg1 = NULL;
}
{
  _arg1 = &temp;
}
    if(!PyArg_ParseTuple(args,"O:HrOpenExchangePrivateStore",&_obj0)) 
        return NULL;
{
	if (!PyCom_InterfaceFromPyInstanceOrObject(_obj0, IID_IMAPISession, (void **)&_arg0, 0))
		return NULL;
}
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )HrOpenExchangePrivateStore(_arg0,_arg1);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           {
	if (_arg0) _arg0->Release();
}

#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
	MAKE_OUTPUT_INTERFACE(_arg1, _resultobj, IID_IMsgStore)
}
{
	if (_arg0) _arg0->Release();
}
    return _resultobj;
}

static PyObject *_wrap_HrOpenExchangePublicFolders(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    IMsgStore * _arg0;
    IMAPIFolder ** _arg1;
    IMAPIFolder * temp;
    PyObject * _obj0 = 0;

    self = self;
{
  _arg1 = &temp;
}
    if(!PyArg_ParseTuple(args,"O:HrOpenExchangePublicFolders",&_obj0)) 
        return NULL;
{
	if (!PyCom_InterfaceFromPyInstanceOrObject(_obj0, IID_IMsgStore, (void **)&_arg0, 0))
		return NULL;
}
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )HrOpenExchangePublicFolders(_arg0,_arg1);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           {
	if (_arg0) _arg0->Release();
}

#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
	MAKE_OUTPUT_INTERFACE(_arg1, _resultobj, IID_IMAPIFolder)
}
{
	if (_arg0) _arg0->Release();
}
    return _resultobj;
}

static PyObject *_wrap_HrOpenSessionObject(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    IMAPISession * _arg0;
    IMAPIProp ** _arg1;
    IMAPIProp * temp;
    PyObject * _obj0 = 0;

    self = self;
{
	_arg0 = NULL;
}
{
  _arg1 = &temp;
}
    if(!PyArg_ParseTuple(args,"O:HrOpenSessionObject",&_obj0)) 
        return NULL;
{
	if (!PyCom_InterfaceFromPyInstanceOrObject(_obj0, IID_IMAPISession, (void **)&_arg0, 0))
		return NULL;
}
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )HrOpenSessionObject(_arg0,_arg1);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           {
	if (_arg0) _arg0->Release();
}

#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
	MAKE_OUTPUT_INTERFACE(_arg1, _resultobj, IID_IMAPIProp)
}
{
	if (_arg0) _arg0->Release();
}
    return _resultobj;
}

static PyObject *_wrap_HrOpenSiteContainer(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    IMAPISession * _arg0;
    IMAPIProp ** _arg1;
    IMAPIProp * temp;
    PyObject * _obj0 = 0;

    self = self;
{
	_arg0 = NULL;
}
{
  _arg1 = &temp;
}
    if(!PyArg_ParseTuple(args,"O:HrOpenSiteContainer",&_obj0)) 
        return NULL;
{
	if (!PyCom_InterfaceFromPyInstanceOrObject(_obj0, IID_IMAPISession, (void **)&_arg0, 0))
		return NULL;
}
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )HrOpenSiteContainer(_arg0,_arg1);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           {
	if (_arg0) _arg0->Release();
}

#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
	MAKE_OUTPUT_INTERFACE(_arg1, _resultobj, IID_IMAPIProp)
}
{
	if (_arg0) _arg0->Release();
}
    return _resultobj;
}

static PyObject *_wrap_HrOpenSiteContainerAddressing(PyObject *self, PyObject *args) {
    PyObject * _resultobj;
    HRESULT  _result;
    IMAPISession * _arg0;
    IMAPIProp ** _arg1;
    IMAPIProp * temp;
    PyObject * _obj0 = 0;

    self = self;
{
	_arg0 = NULL;
}
{
  _arg1 = &temp;
}
    if(!PyArg_ParseTuple(args,"O:HrOpenSiteContainerAddressing",&_obj0)) 
        return NULL;
{
	if (!PyCom_InterfaceFromPyInstanceOrObject(_obj0, IID_IMAPISession, (void **)&_arg0, 0))
		return NULL;
}
{
      Py_BEGIN_ALLOW_THREADS
          _result = (HRESULT )HrOpenSiteContainerAddressing(_arg0,_arg1);

      Py_END_ALLOW_THREADS
      if (FAILED(_result))  {
           {
	if (_arg0) _arg0->Release();
}

#ifdef SWIG_THIS_IID
           return PyCom_BuildPyException(_result, _swig_self,  SWIG_THIS_IID);
#else
           return PyCom_BuildPyException(_result);
#endif
      }
}{
	_resultobj = Py_None;
	Py_INCREF(Py_None);
}
{
	MAKE_OUTPUT_INTERFACE(_arg1, _resultobj, IID_IMAPIProp)
}
{
	if (_arg0) _arg0->Release();
}
    return _resultobj;
}

static PyMethodDef exchangeMethods[] = {
	 { "HrOpenSiteContainerAddressing", _wrap_HrOpenSiteContainerAddressing, 1 },
	 { "HrOpenSiteContainer", _wrap_HrOpenSiteContainer, 1 },
	 { "HrOpenSessionObject", _wrap_HrOpenSessionObject, 1 },
	 { "HrOpenExchangePublicFolders", _wrap_HrOpenExchangePublicFolders, 1 },
	 { "HrOpenExchangePrivateStore", _wrap_HrOpenExchangePrivateStore, 1 },
	 { "HrOpenExchangePublicStore", _wrap_HrOpenExchangePublicStore, 1 },
	 { "HrMAPISetPropLong", _wrap_HrMAPISetPropLong, 1 },
	 { "HrMAPISetPropBoolean", _wrap_HrMAPISetPropBoolean, 1 },
	 { "HrMAPIOpenFolderEx", _wrap_HrMAPIOpenFolderEx, 1 },
	 { "HrMailboxLogoff", _wrap_HrMailboxLogoff, 1 },
	 { "HrMailboxLogon", _wrap_HrMailboxLogon, 1 },
	 { "HrFindExchangeGlobalAddressList", PyHrFindExchangeGlobalAddressList, 1 },
	 { "HrCreateDirEntryIdEx", PyHrCreateDirEntryIdEx, 1 },
	 { "HrCreateProfileName", PyHrCreateProfileName, 1 },
	 { "HrMAPIFindStore", PyHrMAPIFindStore, 1 },
	 { "HrMAPIFindFolderEx", PyHrMAPIFindFolderEx, 1 },
	 { "HrMAPIFindFolder", PyHrMAPIFindFolder, 1 },
	 { "HrMAPIFindSubfolderEx", _wrap_HrMAPIFindSubfolderEx, 1 },
	 { "HrMAPIFindInbox", PyHrMAPIFindInbox, 1 },
	 { "HrMAPIFindIPMSubtree", PyHrMAPIFindIPMSubtree, 1 },
	 { "HrMAPIFindDefaultMsgStore", PyHrMAPIFindDefaultMsgStore, 1 },
	 { "HrGetServerDN", _wrap_HrGetServerDN, 1 },
	 { "HrGetMailboxDN", _wrap_HrGetMailboxDN, 1 },
	 { "HrGetExchangeStatus", _wrap_HrGetExchangeStatus, 1 },
	 { NULL, NULL }
};
static PyObject *SWIG_globals;
#ifdef __cplusplus
extern "C" 
#endif
#if (PY_VERSION_HEX < 0x03000000)
#define MODINIT_ERROR_RETURN
SWIGEXPORT(void,initexchange)() {
#else
#define MODINIT_ERROR_RETURN NULL
SWIGEXPORT(PyObject*,  PyInit_exchange)(void) {
#endif
	 PyObject *m, *d;
	 SWIG_globals = SWIG_newvarlink();
#if (PY_VERSION_HEX < 0x03000000)
	 m = Py_InitModule("exchange", exchangeMethods);
	 d = PyModule_GetDict(m);
#else
  static PyModuleDef exchange_def = {
    PyModuleDef_HEAD_INIT,
      "exchange",
      "",
      -1,
      exchangeMethods,
      };
  m = PyModule_Create(&exchange_def);
  if (!m)
    return NULL;
  d = PyModule_GetDict(m);
  if (!d)
    return NULL;
#endif

#ifndef SWIG_PYTHONCOM
/* This code only valid if non COM SWIG builds */
#ifndef PYCOM_EXPORT
	 PyDict_SetItemString(d,"UNICODE", PyInt_FromLong(
#ifdef UNICODE
	1
#else
	0
#endif
	));
#endif
  PyWinGlobals_Ensure();
  PyDict_SetItemString(d, "error", PyWinExc_ApiError);
#endif SWIG_PYTHONCOM
	 PyDict_SetItemString(d,"OPENSTORE_USE_ADMIN_PRIVILEGE", PyInt_FromLong((long) OPENSTORE_USE_ADMIN_PRIVILEGE));
	 PyDict_SetItemString(d,"OPENSTORE_PUBLIC", PyInt_FromLong((long) OPENSTORE_PUBLIC));
	 PyDict_SetItemString(d,"OPENSTORE_HOME_LOGON", PyInt_FromLong((long) OPENSTORE_HOME_LOGON));
	 PyDict_SetItemString(d,"OPENSTORE_TAKE_OWNERSHIP", PyInt_FromLong((long) OPENSTORE_TAKE_OWNERSHIP));
	 PyDict_SetItemString(d,"OPENSTORE_OVERRIDE_HOME_MDB", PyInt_FromLong((long) OPENSTORE_OVERRIDE_HOME_MDB));

	if ( PyCom_RegisterClientType(&PyIExchangeManageStore::type, &IID_IExchangeManageStore) != 0 ) return MODINIT_ERROR_RETURN;
	ADD_IID(IID_IExchangeManageStore);
#if (PY_VERSION_HEX > 0x03000000)
	return m;
#endif
}
