
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "94b0c251d65306b3fc7da00c33e0413d88b9d2b3",
 "version": "0.15.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
